name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Generate the sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        baseUrl: https://simpletoollab.com/
